spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=sub_tracker
    username: ${DATABASE_USER}
    password: ${DATABSE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog.xml
    liquibase-schema: sub_tracker
    default-schema: sub_tracker
  jpa:
    show-sql: false
server:
  port: ${PORT:8080}
