spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sub_tracker
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog.xml
    liquibase-schema: sub_tracker
    default-schema: sub_tracker
  jpa:
    show-sql: true
server:
  port: 8080
